apiVersion: v1
kind: ServiceAccount
metadata:
  name: helix-app-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helix-app.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::725537514357:role/helix-app-irsa-role
automountServiceAccountToken: true
